extends SceneTree

# Renders the read-only character content report from ContentIndex.
#
#   godot --headless --path . -s res://scripts/content_report.gd
#   godot --headless --path . -s res://scripts/content_report.gd -- --output content_report.md
#
# Exits non-zero only when the index reports an error-severity issue, so this can
# double as a CI gate without duplicating CharacterValidator's logic.

const PACKAGE_ROOT := "res://content/characters"

func _init() -> void:
    call_deferred("_run")

func _run() -> void:
    var output_path := _argument_value("--output")
    var manifests := _load_manifests()
    if manifests.is_empty():
        push_error("Content report: no character packages found")
        quit(1)
        return

    var index := ContentIndex.new()
    index.build(manifests, CharacterValidator.load_unbound_allowlist())

    # verify.sh wants the verdict, not the whole document.
    if _has_flag("--issues-only"):
        for issue: Dictionary in index.issues():
            print("%s [%s] %s: %s" % [
                issue["severity"].to_upper(),
                issue["code"],
                String(issue["character_id"]),
                issue["message"],
            ])
        _report_counts(index)
        return

    var markdown := _render(index)
    if output_path.is_empty():
        print(markdown)
    else:
        var file := FileAccess.open(output_path, FileAccess.WRITE)
        if file == null:
            push_error("Content report: cannot write %s" % output_path)
            quit(1)
            return
        file.store_string(markdown)
        file.close()
        print("Content report written: %s" % output_path)

    _report_counts(index)

func _report_counts(index: ContentIndex) -> void:
    var error_count := index.issues(ContentIndex.SEVERITY_ERROR).size()
    var warning_count := index.issues().size() - error_count
    print("Content report: %d error(s), %d warning(s)" % [error_count, warning_count])
    quit(1 if error_count > 0 else 0)

func _has_flag(flag: String) -> bool:
    return OS.get_cmdline_user_args().has(flag)

func _load_manifests() -> Array[CharacterManifest]:
    var manifests: Array[CharacterManifest] = []
    var directories := DirAccess.get_directories_at(PACKAGE_ROOT)
    directories.sort()
    for directory: String in directories:
        if directory.begins_with("_"):
            continue
        var manifest_path := "%s/%s/character_manifest.tres" % [PACKAGE_ROOT, directory]
        if not ResourceLoader.exists(manifest_path):
            continue
        var manifest := load(manifest_path) as CharacterManifest
        if manifest != null:
            manifests.append(manifest)
    return manifests

func _render(index: ContentIndex) -> String:
    var lines: Array[String] = []
    lines.append("# Character Content Report")
    lines.append("")
    lines.append("Generated by `scripts/content_report.gd` from ContentIndex, the same join")
    lines.append("CharacterValidator and the editor dock read. SpriteFrames is the truth for")
    lines.append("which animations can play; `MoveData.animation_id` is not read at runtime.")
    lines.append("")
    _render_summary(index, lines)
    for entry: Dictionary in index.characters:
        _render_character(entry, lines)
    return "\n".join(lines) + "\n"

func _render_summary(index: ContentIndex, lines: Array[String]) -> void:
    lines.append("## Summary")
    lines.append("")
    lines.append("| Character | Moves | Bound | Unbound | Animations | Orphan art | Errors |")
    lines.append("| --- | ---: | ---: | ---: | ---: | ---: | ---: |")
    for entry: Dictionary in index.characters:
        var moves: Array = entry["moves"]
        var bound := 0
        for row: Dictionary in moves:
            if row["bound"]:
                bound += 1
        var orphans := 0
        for row: Dictionary in entry["animations"]:
            if not row["referenced"]:
                orphans += 1
        var errors := 0
        for issue: Dictionary in entry["issues"]:
            if issue["severity"] == ContentIndex.SEVERITY_ERROR:
                errors += 1
        lines.append("| %s | %d | %d | %d | %d | %d | %s |" % [
            String(entry["character_id"]),
            moves.size(),
            bound,
            moves.size() - bound,
            (entry["animations"] as Array).size(),
            orphans,
            "**%d**" % errors if errors > 0 else "0",
        ])
    lines.append("")

func _render_character(entry: Dictionary, lines: Array[String]) -> void:
    lines.append("## %s (`%s`)" % [entry["display_name"], String(entry["character_id"])])
    lines.append("")
    if not entry.get("move_fallback_exists", true):
        lines.append("> Unbound moves render nothing: this package has no `%s` animation to fall back to." % String(ContentIndex.MOVE_FALLBACK_ANIMATION))
        lines.append("")

    lines.append("### Moves")
    lines.append("")
    lines.append("| Move | Animation | Startup | Active | Recovery | Damage | Status |")
    lines.append("| --- | --- | ---: | ---: | ---: | ---: | --- |")
    for row: Dictionary in entry["moves"]:
        lines.append("| `%s` | %s | %d | %d | %d | %d | %s |" % [
            String(row["move_id"]),
            _binding_summary(row["bindings"]),
            row["startup_frames"],
            row["active_frames"],
            row["recovery_frames"],
            row["damage"],
            _move_status(row),
        ])
    lines.append("")

    lines.append("### States")
    lines.append("")
    lines.append("| State | Animation |")
    lines.append("| --- | --- |")
    for row: Dictionary in entry["states"]:
        lines.append("| `%s` | %s |" % [String(row["state_key"]), _binding_summary(row["bindings"])])
    lines.append("")

    var orphans: Array[String] = []
    for row: Dictionary in entry["animations"]:
        if not row["referenced"]:
            orphans.append("`%s`" % String(row["animation_key"]))
    if not orphans.is_empty():
        lines.append("### Built art nothing references (%d)" % orphans.size())
        lines.append("")
        lines.append(", ".join(orphans))
        lines.append("")

    var issues: Array = entry["issues"]
    if not issues.is_empty():
        lines.append("### Issues")
        lines.append("")
        for issue: Dictionary in issues:
            lines.append("- **%s** `%s` — %s" % [issue["severity"], issue["code"], issue["message"]])
        lines.append("")

func _binding_summary(bindings: Array) -> String:
    if bindings.is_empty():
        return "_(none)_"
    var parts: Array[String] = []
    for binding: Dictionary in bindings:
        var text := "`%s`" % String(binding["animation_key"])
        if not binding["exists"]:
            text += " **MISSING**"
        if String(binding["resource_id"]) != "":
            text += " _(%s %d-%d)_" % [String(binding["resource_id"]), binding["resource_min_value"], binding["resource_max_value"]]
        parts.append(text)
    return "<br>".join(parts)

func _move_status(row: Dictionary) -> String:
    if not row["bound"]:
        return "allowlisted unbound" if row["allowlisted"] else "**UNBOUND**"
    for binding: Dictionary in row["bindings"]:
        if not binding["exists"]:
            return "**MISSING ANIMATION**"
    return "ok"

func _argument_value(flag: String) -> String:
    var arguments := OS.get_cmdline_user_args()
    for index in range(arguments.size() - 1):
        if arguments[index] == flag:
            return arguments[index + 1]
    return ""
